### ISSUE TITLE
Handle cases where <entityId> contains a Wikidata identifier

### ISSUE THREAD

**Issue by tfrancart** [ArchivesNationalesFR/rico-converter#15]
> EAC to RiC-O : Prendre en compte le cas de entityId ayant pour valeur un id Wikidata (use case AN) (similaire BNF et SIRET)

**Comment by tfrancart** [comment]
@florenceclavaud pourras-tu créer un test unitaire pour cela ?

**Comment by florenceclavaud** [comment]
> @florenceclavaud pourras-tu créer un test unitaire pour cela ?

Oui, on crée une branche pour ça ?

**Comment by tfrancart** [comment]
Oui je viens de créer la brance `issue-15-wikidata"

**Comment by florenceclavaud** [comment]
I have just pushed the new unit test to the branch
