### ISSUE TITLE
New version of organization types (remove LegalStatus from the conversion)

### ISSUE THREAD

**Issue by tfrancart** [ArchivesNationalesFR/rico-converter#16]
> EAC to RiC-O : Prendre en compte la nouvelle version du vocabulaire des types d’organismes (supprimer le vocabulaire LegalStatus de la conversion)

**Comment by florenceclavaud** [comment]
Yes the unit tests have to be updated. The URI of the target CorporateBodyType should now be as follows:
corporateBodyType/FRAN_RI_104-{string}
the string being the value of legalStatus/term/@vocabularySource in the source file.

**Comment by tfrancart** [comment]
Similaire à OccupationType:

```xml
<xsl:function name="eac2rico:URI-OccupationType">
		<xsl:param name="vocabularySource" />
		<xsl:value-of select="concat('occupationType/', 'FRAN_RI_010-', $vocabularySource)" />
	</xsl:function>
```
