### ISSUE TITLE
Migrate documentation to Github pages

### ISSUE THREAD

**Issue by tfrancart** [ArchivesNationalesFR/rico-converter#19]

**Comment by tfrancart** [comment]
@florenceclavaud : I have copied the documentation under `/docs` directory and configured the generation of the site through a Github Action workflow. The documentation is correctly published at https://archivesnationalesfr.github.io/rico-converter/, with basic styling. I am not quite sure how to customize header/footer or CSS with the new Github Actions workflows, this requires a bit more investigation.

Let's talk about it and when we are happy I will delete the existing documentation generation steps from the existing compilation process.

**Comment by florenceclavaud** [comment]
OK let us talk about is soon (I would be happy to understand how you did this better). Even with this simple layout I think having a website is really better.

**Comment by tfrancart** [comment]
@florenceclavaud All the configuration and the magic happens here : https://github.com/ArchivesNationalesFR/rico-converter/blob/master/.github/workflows/jekyll-gh-pages.yml

**Comment by tfrancart** [comment]
OK : delete previous version of the doc

**Comment by tfrancart** [comment]
Old version of the doc has been deleted.
I close this issue and will open a separate one to migrate README
