### ISSUE TITLE
Update documentation with latest enhancements

### ISSUE THREAD

**Issue by tfrancart** [ArchivesNationalesFR/rico-converter#20]

**Comment by tfrancart** [comment]
TODO:

- update mapping files (including rules for specific props, etc.)
- update and/or complement example files in the input_ead and input_eac folder

**Comment by tfrancart** [comment]
Other TODOs :

- Update to RiC-O 0.2
- Addition of shortcuts
- How to use the "driver" XSLT
- Better check for empty elements and URLs
- Update a few controlled vocabularies (+link to github of referential)
- in About section, check for references, including webinars and link to the article

**Comment by tfrancart** [comment]
Thomas:

- Addition of shortcuts
- How to use the "driver" XSLT
- Better check for empty elements and URLs

AN Labs:

- Update to RiC-O 0.2
- Update a few controlled vocabularies (+link to github of referential)
- in About section, check for references, including webinars and link to the article

**Comment by tfrancart** [comment]
- Also include which XML elements are **not** processed
- Document specificities of the files of the AN (otherlevel, controlled vocabularies, etc.)

**Comment by florenceclavaud** [comment]
> AN Labs:
> 
>     * Update to RiC-O 0.2
> 
>     * Update a few controlled vocabularies (+link to github of referential)
> 
>     * in About section, check for references, including webinars and link to the article

Hi @tfrancart, this is done.

**Comment by tfrancart** [comment]
Actually, these documentation will be part of the release note (see latest release draft)

**Comment by florenceclavaud** [comment]
> TODO:
> 
>     * [ ]  update mapping files (including rules for specific props, etc.)
> 
Done as concerns the EAC to RiC-O mapping file.

**Comment by tfrancart** [comment]
@florenceclavaud I have beautified the mapping files a bit (did not change anything on the content) and merged the branch to master.

**Comment by florenceclavaud** [comment]
> @florenceclavaud I have beautified the mapping files a bit (did not change anything on the content) and merged the branch to master.

Thank you, this is better!
