### ISSUE TITLE
Handle the case where entityId has a localType attribute with values "numéro RNA", "numéro SIREN" or "numéro SIRET"

### ISSUE THREAD

**Issue by florenceclavaud** [ArchivesNationalesFR/rico-converter#28]
These are quite recently added values for this attribute in the ANF information system.

For now, RiC-O Converter only takes into account, for this localType attribute, the "ISNI" value, + the  "Wikidata" one (see #15). 
It also handles the following case: 

`<entityId>SIRET` 501 524 029 `00086</entityId>`

not more.

**Comment by tfrancart** [comment]
@florenceclavaud would you mind creating unit tests on the newly created branch issue-28-entityId ? (similar to Wikidata one) thanks

**Comment by florenceclavaud** [comment]
And done for the SIREN and RNA identifiers (added two unit tests for this). The only cases found in the ANF files rely on the values of the localType attributes.

**Comment by tfrancart** [comment]
Thomas can implement based on unit tests

**Comment by tfrancart** [comment]
@florenceclavaud Implementation, done, to be reviewed
