### ISSUE TITLE
Renaming and refactoring to generate new properties hasContentOfType, hasOrHadLanguage, hasOrHadLegalStatus, hasRecordState

### ISSUE THREAD

**Issue by tfrancart** [ArchivesNationalesFR/rico-converter#4]
Necessitate a refactoring of the RecordSet.
See also #3 

> Une attention particulière doit être apportée aux propriétés suivantes : hasContentOfType,
> hasOrHadLanguage (qui remplace HasLanguage), hasOrHadLegalStatus (qui remplace
> hasLegalStatus), hasRecordState (qui remplace hasRecordResourceState). Le domaine de ces
> propriétés a été réduit aux classes Record et Record Part (et Agent pour les propriétés
> hasOrHadLanguage et hasOrHadLegalStatus) alors qu’il était autrefois fixé à RecordResource.

And also:

> Pour la classe RecordSet, de nouvelles propriétés ont été introduites. Par ex., pour relier un
> RecordSet et un Language, on utilise désormais les propriétés suivantes :
> hasOrHadAllMembersWithLanguage
> hasOrHadSomeMembersWithLanguage
> Voir à ce sujet le ticket https://github.com/ICA-EGAD/RiC-O/issues/20
> Ce qui conduira dans RiC-O Converter à réécrire les instructions correspondantes.

**Comment by tfrancart** [comment]
| Property on Record ou RecordPart | Property on RecordSet |
|----------------------------|-------------------------------|
| hasOrHadLanguage|hasOrHadSomeMembersWithLanguage (or hasOrHadAllMembersWithLanguage if there is only one value)|
| hasOrHadDocumentaryFormType|hasOrHadSomeMembersWithDocumentaryFormType (always as even if there is a single value this does not mean that every record of the record set has this documentary form type)|
|hasOrHadLegalStatus|hasOrHadSomeMembersWithLegalStatus (or hasOrHadAllMembersWithLegalStatus if there is only one value)|
|hasOrHadRecordState|hasOrHadSomeMembersWithRecordState (always as even if there is a single value this does not mean that every record of the record set has this record state)|
|hasOrHadContentType|hasOrHadSomeMembersWithContentType (always as even if there is a single value this does not mean that every record of the record set has this content type)|

**Comment by tfrancart** [comment]
In case where we can't determine the precise type of the resource, a possibility would be to use more generic, non-RiC-O properties, such as DublinCore : e.g. dct:language. To be analyzed for others

**Comment by tfrancart** [comment]
@florenceclavaud I cannot find hasLegalStatus, hasRecordResourceState and hasContentOfType in the current EAD XSLT.

We use hasLegalStatus but on EAC conversion to descrive Agents, see here https://github.com/ArchivesNationalesFR/rico-converter/blob/master/ricoconverter/ricoconverter-convert/src/test/resources/eac2rico/_23legalStatus/expected.xml#L23.

I can't find any occurrence of hasRecordResourceState.

I can't find any occurrence of hasContentOfType.

**Comment by tfrancart** [comment]
Done for hasDocumentaryFormType, still TODO for hasLanguage.

**Comment by florenceclavaud** [comment]
> @florenceclavaud I cannot find hasLegalStatus, hasRecordResourceState and hasContentOfType in the current EAD XSLT.
> 
> We use hasLegalStatus but on EAC conversion to descrive Agents (which is legal usage), see here https://github.com/ArchivesNationalesFR/rico-converter/blob/master/ricoconverter/ricoconverter-convert/src/test/resources/eac2rico/_23legalStatus/expected.xml#L23.
> 
> I can't find any occurrence of hasRecordResourceState.
> 
> I can't find any occurrence of hasContentOfType.

Hi @tfrancart, yes you're right about legalstatus in EAD files. While EAD 2002 defines a legalstatus element, we do not use it in the ANF for now (which does not mean that we should not think of doing something about it in the converter; I suggest we discuss this later on). We use legalStatus  in EAC-CPF, but in such a case it concerns corporate bodies, and does is not related to this issue (see also #18).

**Comment by florenceclavaud** [comment]
About DocumentaryFormType and RecordState (no ContentType for now):
Things are a bit more complicated in fact, as we know have three SKOS/RiC-O vocabularies, one for the DocumentaryFormTypes, one for the RecordSetTypes, and one for the RecordStates (see [https://github.com/ArchivesNationalesFR/Referentiels/tree/main/concepts/rdf](https://github.com/ArchivesNationalesFR/Referentiels/tree/main/concepts/rdf) . And as in our EAD files, the only element used for recording such types is genreform.
I would say:
- if the record resource is a Record or a Record Part: if genreform/@authfilenumber refers to a skos:Concept in the DocumentaryFormTypes vocabulary, use hasDocumentaryFormType (with a warning if there is more than one genreform of the kind) ; if genreform/@authfilenumber refers to a skos:RecordState in the RecordStates vocabulary, use hasRecordState; in any other case (e.g. a reference to the RecordSetTypes vocabulary) do nothing and generate a warning
- if the record resource is a Record Set: if genreform/@authfilenumber refers to a skos:Concept in the RecordSetTypes vocabulary, generate a hasRecordSetType (with a warning if there is more than one genreform of the kind); if genreform/@authfilenumber refers to a skos:Concept in the DocumentaryFormTypes vocabulary, use hasOrHadSomeMembersWithDocumentaryFormType  as said above ; if genreform/@authfilenumber refers to a skos:RecordState in the RecordStates vocabulary, use hasOrHadSomeMembersWithRecordState as said above
- if the record resource is neither a Record, or a Record Part or a Record Set and there is a genreform: the value of genreform/@authfilenumber could help infer what it is - however it may be quite risky when it is from the whole of our data... I would generate a warning
Obviously this is a case where SHACL could also help to analyze the output, check if everything is consistent, and see if we can decide to reason about this.
Note that we do not have hasOrHadDocumentaryFormType nor hasOrHadRecordState or hasOrHadContentOfType (a Record or Record Part does not change such categories through time). Sorry I had not seen this.
@tfrancart what do you think?

**Comment by tfrancart** [comment]
This is now implemented. I have kept dc:type as a default value with the literal name of the genreform in case the value is not found in any of the vocabulary.

**Comment by tfrancart** [comment]
1. Ajouter rico:type en plus de dc:type.
2. Ajouter un warning si le type de la resource n'est pas reconnu
