### ISSUE TITLE
Typo in ricoconverter.sh 

### ISSUE THREAD

**Issue by LuciaGiagnolini12** [ArchivesNationalesFR/rico-converter#52]
Hi! I'm testing the converter in a Mac environment and it seems to me that there is a little typo in the "ricoconverter.sh" file. 
At line 23 appears a "@" that causes an error while trying to launch a command, since it seems to interfere with the file path, giving e.g. the error: 

> "ERROR : Could not read file @parameters/convert_eac.properties: java.nio.file.NoSuchFileException: @parameters/convert_eac.properties"

I tried and deleted the "@" at line 23 and the file works correctly. But I'm not an expert at all, so I wanted to check with you the correctness of this change.
Thank you very much!
Lucia

**Comment by tfrancart** [comment]
Thank you (we mostly tested on Windows). This has been fixed in a new 2.0.2 release
