### ISSUE TITLE
Modification de rico:descriptiveNote en rico:generalDescription

### ISSUE THREAD

**Issue by tfrancart** [ArchivesNationalesFR/rico-converter#55]

**Comment by tfrancart** [comment]
Thomas:
- lister les règles XSLT qui génèrent cette propriété (dans les 2 XSLT)
- lister les valeurs que l'on trouve dans le jeu de test

l'alternative serait des relations vers des ressources qui seraient des noeuds blancs

**Comment by tfrancart** [comment]
@florenceclavaud voici la liste de tous les endroits où rico-converter produit un `rico:descriptiveNote` :



## Dans l'EAD

- balise `note` sur le findingaid
- balise `change` qui produit un rico:Activity qui porte la note
- balise `daodesc`
- balise `otherfindaid`
- balise `relatedmaterial`
- balise `separatedmaterial`
- balise `originalsloc/.../ref` qui génère un rico:hasGeneticLinkToRecordResource/rico:RecordResource qui porte la note
- balise `altformavail`
- balise `bibliography`


## Dans l'EAC

- `eventDescription`
- `structureOrGenealogy`
- Tous les `eac:descriptiveNote` donnent un rico:descriptiveNote, dans :
  - toutes les rico:PlaceRelation
  - mais pas depuis eac:source pour lequel on génère rico:source

**Comment by tfrancart** [comment]
@florenceclavaud Voici une query pour lister les valeurs dans le jeu de test:

```sparql
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
SELECT ?type ?x ?note
WHERE {
    ?x rico:descriptiveNote ?note .
    ?x a ?type .
}
ORDER BY ?type ?x
```

Et voici l'export des 440 valeurs de rico:descriptiveNote:

[query-result.csv](https://github.com/user-attachments/files/17408657/query-result.csv)

A partir de là @florenceclavaud je te laisse m'indiquer sur quels éléments tu voudrais transformer descriptiveNote en generalDescription

**Comment by tfrancart** [comment]
On remplace toutes les occurrences par rico:generalDescription

**Comment by florenceclavaud** [comment]
On a maintenant dans RiC-O (on plutôt on aura dans RiC-O 1.1 dont la release sera faite courant février) une datatype property rico:note. Voir la PR [https://github.com/ICA-EGAD/RiC-O/pull/133](https://github.com/ICA-EGAD/RiC-O/pull/133).

Je pense qu'il faudrait passer de rico:generalDescription à rico:note dans les cas suivants, sans changer la logique (on change juste la propriété générée) :

- Fichiers EAC 

eac:function/eac:descriptiveNote 
eac:occupation/eac:descriptiveNote
eac:legalStatus/eac:descriptiveNote
eac:place/eac:descriptiveNote
eac:mandate/eac:descriptiveNote (quand cette donnée est conservée)
toutes les relations eac (cpfRelation, resourceRelation)

- Fichiers EAD
eadheader/fileDesc/notestmt/note
