### ISSUE TITLE
Rolification des relations : remplacer les prédicats utilisés dans les relations par les nouvelles propriétés RiC-O 1.0

### ISSUE THREAD

**Issue by tfrancart** [ArchivesNationalesFR/rico-converter#59]

**Comment by tfrancart** [comment]
relationHasSource et relationHasTarget à la place des relations actuelles (à revérifier)

**Comment by tfrancart** [comment]
Checked predicates : `rico:relationHasSource` and `rico:relationHasTarget` and `rico:relationConnects` and `rico:thingIsSourceOfRelation` + `rico:thingIsTargetOfRelation` + `rico:thingIsConnectedToRelation`

**Comment by florenceclavaud** [comment]
@tfrancart, il y aurait d'autres propriétés de relations à modifier dans les données RDF : celles qui concernent, pour les notices d'agents, les fonctions et activités (PerformanceRelation), les types de collectivités (TypeRelation), les archives (AgentOriginationRelation, qu'il faut par ailleurs remplacer par OrganicProvenanceRelation ; de plus la propriété isProvenanceOf a été renommée dans RiC-O 1.0.2 isOrganicProvenanceOf), les mandats (MandateRelation) et les lieux (PlaceRelation). Il y a aussi les relations temporelles entre agents (AgentTemporalRelation). 
Pour les fichiers EAD, je n'ai rien vu, sauf la propriété hasProvenance à remplacer par hasOrganicProvenance.
