### ISSUE TITLE
Utilisation de propriétés plus précises pour lier RecordResource et Instantiation

### ISSUE THREAD

**Issue by tfrancart** [ArchivesNationalesFR/rico-converter#60]
Actuellement : `hasInstantiation`
On voudrait `hasOrHadAnalogueInstantiation` ou `hasorHadDigitalInstantiation`

- en fonction de la présention de dao ou daoGroup : alors c'est forcément digital
- autres cas : instruments de recherche qui décrivent des archives nativement numériques; on ne sait pas si on peut détecter ces cas

**Comment by tfrancart** [comment]
1. tester sur les dao ou daoGroup et changer en `hasOrHadDigitalInstantiation`
2. tester `physfacet[@type = 'd3nd9y3c6o-iu0j3xsmoisx' ]`alors c'est `hasOrHadDigitalInstantiation`
3.  Sinon la propriété de base devient `rico:hasOrHadInstantiation`

**Comment by florenceclavaud** [comment]
> @florenceclavaud
> 
>     * l'instantiation du Findingiad est toujours référencée avec `hasOrHadDigitalInstantiation` car c'est un XML
> 
>     * les instantiation des Record EAC sont toujours référencées avec `hasOrHadDigitalInstantiation` car ce sont des XML
> 
> 
> OK pour toi ?

Désolée je n'avais pas vu ta question. Oui c'est ça !
